import type { ClaudeScope } from "../types.js";

export function normalizeClaudeScope(raw: string | undefined): ClaudeScope {
  const s = (raw ?? "project").toLowerCase().trim();
  if (s === "global" || s === "local") return s;
  return "project";
}

/** Path relative to the project output directory (or logical path for display). */
export function claudeRelativeFilename(scope: ClaudeScope): string {
  if (scope === "local") return ".claude/CLAUDE.local.md";
  return ".claude/CLAUDE.md";
}

/**
 * HTML comment prepended to generated Claude markdown.
 */
export function skillsmithClaudeHeader(scope: ClaudeScope): string {
  const rerun =
    scope === "project" ? "skillsmith . --yes" : `skillsmith --scope=${scope} . --yes`;
  return `<!-- Generated by Skillsmith. Scope: ${scope}. Re-run: ${rerun} -->\n\n`;
}
